-- =====================================================
-- V10__homework_assignment_files.sql
-- 作业发布附件：管理员/部长发布的作业资料附件
-- 与 homework_submission_files（成员提交附件）严格区分
-- =====================================================

CREATE TABLE IF NOT EXISTS homework_assignment_files (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id   BIGINT              NOT NULL REFERENCES homework_assignments(id),
    file_id         BIGINT              NOT NULL REFERENCES files(id),
    created_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_homework_assignment_files_assignment ON homework_assignment_files(assignment_id);
CREATE INDEX IF NOT EXISTS idx_homework_assignment_files_file ON homework_assignment_files(file_id);
