-- =====================================================
-- V1__init.sql
-- 开放原子开源社团秘书处管理系统 初始化表结构
-- H2 兼容版（MODE=PostgreSQL，使用 IDENTITY 自增主键）
-- =====================================================

-- 1. members 成员表
CREATE TABLE IF NOT EXISTS members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)        NOT NULL,
    student_no  VARCHAR(50)         NOT NULL UNIQUE,
    phone       VARCHAR(20),
    major       VARCHAR(100),
    department  VARCHAR(100),
    position    VARCHAR(50)         NOT NULL DEFAULT '社员',
    created_at  TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_members_student_no ON members(student_no);
CREATE INDEX IF NOT EXISTS idx_members_department ON members(department);

-- 2. point_items 积分项目表
CREATE TABLE IF NOT EXISTS point_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name           VARCHAR(200)        NOT NULL,
    point_value         DECIMAL(10, 2)      NOT NULL DEFAULT 0,
    item_type           VARCHAR(50)         NOT NULL DEFAULT '其他',
    description         TEXT,
    sort_order          INT                 NOT NULL DEFAULT 0,
    enabled             BOOLEAN             NOT NULL DEFAULT TRUE,
    allow_member_apply  BOOLEAN             NOT NULL DEFAULT TRUE,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    created_at          TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_point_items_sort ON point_items(sort_order, id);

-- 3. point_applications 成员活动登记表
CREATE TABLE IF NOT EXISTS point_applications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT              NOT NULL REFERENCES members(id),
    point_item_id   BIGINT              NOT NULL REFERENCES point_items(id),
    status          VARCHAR(20)         NOT NULL DEFAULT 'PENDING',
    submitted_at    TIMESTAMP           NOT NULL DEFAULT NOW(),
    reviewed_at     TIMESTAMP,
    reviewed_by     VARCHAR(100),
    review_comment  TEXT,
    created_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMP,
    CONSTRAINT chk_application_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX IF NOT EXISTS idx_point_applications_member ON point_applications(member_id);
CREATE INDEX IF NOT EXISTS idx_point_applications_status ON point_applications(status);
CREATE INDEX IF NOT EXISTS idx_point_applications_member_item ON point_applications(member_id, point_item_id);

-- 4. point_records 积分记录表
CREATE TABLE IF NOT EXISTS point_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT              NOT NULL REFERENCES members(id),
    point_item_id   BIGINT              REFERENCES point_items(id),
    application_id  BIGINT              REFERENCES point_applications(id),
    score           DECIMAL(10, 2)      NOT NULL,
    reason          TEXT,
    source_type     VARCHAR(20)         NOT NULL,
    operator_name   VARCHAR(100),
    occurred_at     TIMESTAMP           NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMP,
    CONSTRAINT chk_record_source CHECK (source_type IN ('APPLICATION', 'MANUAL'))
);

CREATE INDEX IF NOT EXISTS idx_point_records_member ON point_records(member_id);
CREATE INDEX IF NOT EXISTS idx_point_records_application ON point_records(application_id);

-- 5. archive_links 活动资料归档链接表
CREATE TABLE IF NOT EXISTS archive_links (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200)        NOT NULL,
    archive_year    INT                 NOT NULL,
    archive_type    VARCHAR(50)         NOT NULL DEFAULT '其他',
    url             TEXT                NOT NULL,
    description     TEXT,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    created_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_archive_links_year ON archive_links(archive_year);

-- 6. files 文件元数据表
CREATE TABLE IF NOT EXISTS files (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name   VARCHAR(500)        NOT NULL,
    stored_name     VARCHAR(500)        NOT NULL,
    file_path       TEXT                NOT NULL,
    file_size       BIGINT,
    content_type    VARCHAR(200),
    file_hash       VARCHAR(64),
    module_name     VARCHAR(50)         NOT NULL,
    uploaded_by     VARCHAR(100),
    created_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_files_module ON files(module_name);

-- 7. meeting_minutes 会议纪要表
CREATE TABLE IF NOT EXISTS meeting_minutes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200)        NOT NULL,
    meeting_date    DATE                NOT NULL,
    meeting_year    INT                 NOT NULL,
    meeting_month   INT                 NOT NULL,
    file_id         BIGINT              REFERENCES files(id),
    remark          TEXT,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    created_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_meeting_minutes_year_month ON meeting_minutes(meeting_year, meeting_month);

-- 8. finance_periods 财务月份表
CREATE TABLE IF NOT EXISTS finance_periods (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finance_year    INT                 NOT NULL,
    finance_month   INT                 NOT NULL,
    remark          TEXT,
    created_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_finance_period UNIQUE (finance_year, finance_month)
);

CREATE INDEX IF NOT EXISTS idx_finance_periods_year ON finance_periods(finance_year);

-- 9. finance_files 财务文件表
CREATE TABLE IF NOT EXISTS finance_files (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id       BIGINT              NOT NULL REFERENCES finance_periods(id),
    file_id         BIGINT              NOT NULL REFERENCES files(id),
    file_type       VARCHAR(20)         NOT NULL,
    remark          TEXT,
    created_by      VARCHAR(100),
    created_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMP,
    CONSTRAINT chk_finance_file_type CHECK (file_type IN ('REPORT', 'VOUCHER'))
);

CREATE INDEX IF NOT EXISTS idx_finance_files_period ON finance_files(period_id);

-- 10. operation_logs 操作日志表
CREATE TABLE IF NOT EXISTS operation_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_name       VARCHAR(100),
    operator_department VARCHAR(100),
    operator_position   VARCHAR(50),
    module_name         VARCHAR(50),
    action_type         VARCHAR(50),
    target_id           VARCHAR(100),
    description         TEXT,
    created_at          TIMESTAMP           NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_operation_logs_module ON operation_logs(module_name);
CREATE INDEX IF NOT EXISTS idx_operation_logs_created ON operation_logs(created_at DESC);
