-- V2: 用户认证表
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    member_id   BIGINT REFERENCES members(id),
    enabled     BOOLEAN DEFAULT TRUE,
    last_login_at TIMESTAMP,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_username  ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_member_id ON users(member_id);

-- 登录日志（可选，用于追踪登录行为）
CREATE TABLE IF NOT EXISTS login_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT REFERENCES users(id),
    username       VARCHAR(100),
    success        BOOLEAN NOT NULL,
    failure_reason VARCHAR(255),
    ip_address     VARCHAR(100),
    user_agent     TEXT,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW()
);
