-- =====================================================
-- V5__homework.sql
-- 作业管理模块：作业发布、提交、批改
-- =====================================================

-- 1. homework_assignments 作业表
CREATE TABLE IF NOT EXISTS homework_assignments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(200)        NOT NULL,
    description         TEXT,
    target_type         VARCHAR(20)         NOT NULL DEFAULT 'ALL',
    target_department   VARCHAR(100),
    deadline            TIMESTAMP           NOT NULL,
    status              VARCHAR(20)         NOT NULL DEFAULT 'DRAFT',
    max_points          DECIMAL(10, 2),
    point_item_id       BIGINT              REFERENCES point_items(id),
    created_by_user_id  BIGINT              REFERENCES users(id),
    created_at          TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMP,
    CONSTRAINT chk_homework_target_type CHECK (target_type IN ('ALL', 'DEPARTMENT')),
    CONSTRAINT chk_homework_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CLOSED'))
);

CREATE INDEX IF NOT EXISTS idx_homework_assignments_status ON homework_assignments(status);
CREATE INDEX IF NOT EXISTS idx_homework_assignments_deadline ON homework_assignments(deadline);
CREATE INDEX IF NOT EXISTS idx_homework_assignments_target ON homework_assignments(target_type, target_department);

-- 2. homework_submissions 作业提交表
CREATE TABLE IF NOT EXISTS homework_submissions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    homework_id         BIGINT              NOT NULL REFERENCES homework_assignments(id),
    member_id           BIGINT              NOT NULL REFERENCES members(id),
    content             TEXT,
    status              VARCHAR(20)         NOT NULL DEFAULT 'SUBMITTED',
    submitted_at        TIMESTAMP           NOT NULL DEFAULT NOW(),
    review_comment      TEXT,
    awarded_points      DECIMAL(10, 2),
    reviewed_by_user_id BIGINT              REFERENCES users(id),
    reviewed_at         TIMESTAMP,
    point_record_id     BIGINT              REFERENCES point_records(id),
    created_at          TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMP,
    CONSTRAINT uq_homework_submission UNIQUE (homework_id, member_id),
    CONSTRAINT chk_submission_status CHECK (status IN ('SUBMITTED', 'GRADED'))
);

CREATE INDEX IF NOT EXISTS idx_homework_submissions_homework ON homework_submissions(homework_id);
CREATE INDEX IF NOT EXISTS idx_homework_submissions_member ON homework_submissions(member_id);
CREATE INDEX IF NOT EXISTS idx_homework_submissions_status ON homework_submissions(status);

-- 3. homework_submission_files 作业提交附件关联表
CREATE TABLE IF NOT EXISTS homework_submission_files (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id   BIGINT              NOT NULL REFERENCES homework_submissions(id),
    file_id         BIGINT              NOT NULL REFERENCES files(id),
    created_at      TIMESTAMP           NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_homework_submission_files_submission ON homework_submission_files(submission_id);
CREATE INDEX IF NOT EXISTS idx_homework_submission_files_file ON homework_submission_files(file_id);

-- 4. 扩展 point_records 的 source_type 约束，增加 HOMEWORK 类型
ALTER TABLE point_records DROP CONSTRAINT IF EXISTS chk_record_source;
ALTER TABLE point_records ADD CONSTRAINT chk_record_source CHECK (source_type IN ('APPLICATION', 'MANUAL', 'HOMEWORK'));
