-- =====================================================
-- V6__cohort_base.sql
-- 届次（Cohort）体系：届次表 + 成员/作业绑定届次
-- =====================================================

-- 1. cohorts 届次表
CREATE TABLE IF NOT EXISTS cohorts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year        INT                 NOT NULL UNIQUE,
    enabled     BOOLEAN             NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP           NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP           NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cohorts_year ON cohorts(year);

-- 预置初始届次（旧成员不自动分届，仍为 NULL = 未分届）
INSERT INTO cohorts (year, enabled) VALUES (2025, TRUE);
INSERT INTO cohorts (year, enabled) VALUES (2026, TRUE);

-- 2. members 增加届次归属（可空：历史成员未分届）
ALTER TABLE members ADD COLUMN IF NOT EXISTS cohort_id BIGINT REFERENCES cohorts(id);
CREATE INDEX IF NOT EXISTS idx_members_cohort ON members(cohort_id);

-- 3. homework_assignments 增加届次归属（可空：历史作业未分届）
ALTER TABLE homework_assignments ADD COLUMN IF NOT EXISTS cohort_id BIGINT REFERENCES cohorts(id);
CREATE INDEX IF NOT EXISTS idx_homework_assignments_cohort ON homework_assignments(cohort_id);
