-- =====================================================
-- V7__cohort_business_scope.sql
-- 届次业务范围：活动归档多届 + 积分项目适用届次
-- =====================================================

-- 1. archive_cohorts 活动归档届次关系表（多对多）
CREATE TABLE IF NOT EXISTS archive_cohorts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id  BIGINT              NOT NULL REFERENCES archive_links(id),
    cohort_id   BIGINT              NOT NULL REFERENCES cohorts(id),
    created_at  TIMESTAMP           NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_archive_cohort UNIQUE (archive_id, cohort_id)
);

CREATE INDEX IF NOT EXISTS idx_archive_cohorts_cohort ON archive_cohorts(cohort_id);
CREATE INDEX IF NOT EXISTS idx_archive_cohorts_archive ON archive_cohorts(archive_id);

-- 双写回填：把已有 archive_links 按其 archive_year 关联到同年的 cohort（若存在）
INSERT INTO archive_cohorts (archive_id, cohort_id)
SELECT a.id, c.id FROM archive_links a JOIN cohorts c ON c.year = a.archive_year;

-- 2. point_item_cohorts 积分项目适用届次关系表（多对多；0 条关联 = 全局适用）
CREATE TABLE IF NOT EXISTS point_item_cohorts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_item_id   BIGINT              NOT NULL REFERENCES point_items(id),
    cohort_id       BIGINT              NOT NULL REFERENCES cohorts(id),
    created_at      TIMESTAMP           NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_point_item_cohort UNIQUE (point_item_id, cohort_id)
);

CREATE INDEX IF NOT EXISTS idx_point_item_cohorts_cohort ON point_item_cohorts(cohort_id);
CREATE INDEX IF NOT EXISTS idx_point_item_cohorts_item ON point_item_cohorts(point_item_id);
